### ISSUE TITLE
Not able to see effected parameters

### ISSUE THREAD

**Issue by s0meguy1** [msrkp/PPScan#11]
Hi -

This may be "user error" but I am not able to see which parameters are vulnerable within the extension box like in the example you provided in the README.md. I can find the effected parameters if I go back through the burp history, but it would be easier to see in the extension output box. Again, it could be something on my end - I am using the version of Chrome that comes with Burp Suite Pro (90.0.4430.93). I have attached a screenshot of what I mean, what you see in the screenshot is the only data available to me, I am not able to expand on any of the categories. <br>
![aa](https://user-images.githubusercontent.com/25542926/116995936-b53ba400-aca8-11eb-80d7-12b6d1f62ddd.PNG)

**Comment by msrkp** [comment]
Hi @s0meguy1,

The results showed in the table are reported by passive mode, which scans for all the js files for PP fingerprint. It doesn't give the URL with PP payload rather it gives the location in the js file where the fingerprint was found. Sometimes it may find false positives, so I suggest you debug and check if it's vulnerable.
